package closeai.application.autoschedule;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import closeai.domain.entities.Activity;
import closeai.domain.entities.ScheduledEvent;
import closeai.domain.valueobjects.EventType;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * The fingerprint is what stops a Preview being applied over a Day Plan that has moved on
 * since. What it does and does not notice is therefore a correctness question, not a
 * detail: too sensitive and every Preview becomes unusable, too blunt and a stale
 * proposal quietly overwrites newer work.
 */
class ScheduleFingerprintTest {

    private static Activity activity(String id) {
        return ProblemFixtures.activity(id, LocalTime.of(9, 0), LocalTime.of(21, 0));
    }

    private static ScheduledEvent activityEvent(String id, int hour) {
        return new ScheduledEvent(id, activity(id), LocalTime.of(hour, 0),
                LocalTime.of(hour + 1, 0), EventType.ACTIVITY, "");
    }

    private static ScheduledEvent travelEvent(String id, int hour, int minutes) {
        return new ScheduledEvent(id, null, LocalTime.of(hour, 0),
                LocalTime.of(hour, 0).plusMinutes(minutes), EventType.TRAVEL, "Travel");
    }

    @Test
    void theSamePlanAlwaysProducesTheSameFingerprint() {
        List<ScheduledEvent> events = Arrays.asList(activityEvent("a", 9), activityEvent("b", 12));

        assertEquals(ScheduleFingerprint.of(events), ScheduleFingerprint.of(events));
    }

    @Test
    void aChangedStartTimeIsNoticed() {
        assertNotEquals(
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 9))),
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 10))),
                "a Preview built before the user moved something must not be applied");
    }

    @Test
    void anAddedActivityIsNoticed() {
        assertNotEquals(
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 9))),
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 9), activityEvent("b", 12))));
    }

    @Test
    void aRemovedActivityIsNoticed() {
        assertNotEquals(
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 9), activityEvent("b", 12))),
                ScheduleFingerprint.of(Arrays.asList(activityEvent("a", 9))));
    }

    @Test
    void merelyReorderingTheListIsNotAChange() {
        List<ScheduledEvent> one = Arrays.asList(activityEvent("a", 9), activityEvent("b", 12));
        List<ScheduledEvent> other = Arrays.asList(activityEvent("b", 12), activityEvent("a", 9));

        assertEquals(ScheduleFingerprint.of(one), ScheduleFingerprint.of(other),
                "the same activities at the same times are the same plan");
    }

    @Test
    void travelBlocksAreIgnored() {
        List<ScheduledEvent> withoutTravel = Arrays.asList(activityEvent("a", 9));
        List<ScheduledEvent> withTravel = Arrays.asList(
                activityEvent("a", 9), travelEvent("travel-a", 10, 20));

        assertEquals(ScheduleFingerprint.of(withoutTravel), ScheduleFingerprint.of(withTravel),
                "travel is generated by scheduling, not something the user chose, so it "
                        + "must not invalidate a Preview");
    }

    @Test
    void anEmptyPlanHasAStableFingerprint() {
        assertEquals(ScheduleFingerprint.of(Collections.emptyList()),
                ScheduleFingerprint.of(Collections.emptyList()));
    }

    @Test
    void aFingerprintRoundTripsThroughItsStringForm() {
        ScheduleFingerprint original = ScheduleFingerprint.of(
                Arrays.asList(activityEvent("a", 9)));

        assertEquals(original, ScheduleFingerprint.fromValue(original.getValue()),
                "Apply compares the value carried back from the view");
    }

    @Test
    void aMissingValueIsTreatedAsEmptyRatherThanFailing() {
        assertEquals("", ScheduleFingerprint.fromValue(null).getValue());
    }
}
